from system.core.router import routes

routes['default_controller'] = 'Pokes'
routes['POST']['/pokes/add'] = 'Pokes#add'
# routes['GET']['/Pokes/success'] = 'Pokes#success'
routes['POST']['/pokes/login'] = 'Pokes#login'
# routes['GET']['/pokes'] = 'Pokes#pokes'
routes['POST']['/pokes'] = 'Pokes#pokes'
routes['POST']['/pokes/add'] = 'Pokes#pokes_add_one_user'
# routes['POST']['/pokes'] = 'Pokes#success'
routes['GET']['/pokes/logout'] = 'Pokes#logout'
# routes['GET']['/restful/edit/<int:edit_id>'] = 'Restful#edit'
routes['POST']['/pokes/pokes/<int:poke_id>'] = 'Pokes#poke_one_user'
# routes['default_controller'] = 'Pokes'
# routes['POST']['/Pokes/add'] = 'Pokes#add'
# # routes['GET']['/Pokes/success'] = 'Pokes#success'
# routes['POST']['/Pokes/login'] = 'Pokes#login'
# routes['GET']['/Pokes/logout'] = 'Pokes#logout'